KERNEL_NAME := stream_compaction
SRC := $(CURDIR)/src/stream_compaction.cu
CONFIG_DIR := $(CURDIR)/configs
TARGETS_FILE := $(CONFIG_DIR)/target_params.txt
PARAM_DEFINES := MY_BLOCKDIM
VERSION_DEFINE := STREAM_COMPACTION_VARIANT
VERSIONS := 1

include ../../common/kernel.mk
