KERNEL_NAME := prefix_scan
SRC := $(CURDIR)/src/prefix_scan.cu
CONFIG_DIR := $(CURDIR)/configs
TARGETS_FILE := $(CONFIG_DIR)/target_params.txt
PARAM_DEFINES := MY_BLOCKDIM

include ../../common/kernel.mk
