KERNEL_NAME := transpose
SRC := $(CURDIR)/src/transpose.cu
CONFIG_DIR := $(CURDIR)/configs
TARGETS_FILE := $(CONFIG_DIR)/target_params.txt
PARAM_DEFINES :=
VERSION_DEFINE := TRANSPOSE_VARIANT
VERSIONS := 1 2 3 4 5 6

include ../../common/kernel.mk
