KERNEL_NAME := fused_ops
SRC := $(CURDIR)/src/fused_ops.cu
CONFIG_DIR := $(CURDIR)/configs
TARGETS_FILE := $(CONFIG_DIR)/target_params.txt
PARAM_DEFINES := MY_BLOCKDIM
VERSION_DEFINE := FUSED_OPS_VARIANT
VERSIONS := 1

include ../../common/kernel.mk
