KERNEL_NAME := histogram
SRC := $(CURDIR)/src/histogram.cu
CONFIG_DIR := $(CURDIR)/configs
TARGETS_FILE := $(CONFIG_DIR)/target_params.txt
PARAM_DEFINES := MY_BLOCKDIM MY_BIN_COUNT
VERSION_DEFINE := HISTOGRAM_VARIANT
VERSIONS := 1

include ../../common/kernel.mk
