TARGET_NAMES += transpose_1
TARGET_FLAGS_transpose_1 := -DTRANSPOSE_VARIANT=1

TARGET_NAMES += transpose_2
TARGET_FLAGS_transpose_2 := -DTRANSPOSE_VARIANT=2

TARGET_NAMES += transpose_3
TARGET_FLAGS_transpose_3 := -DTRANSPOSE_VARIANT=3

TARGET_NAMES += transpose_4
TARGET_FLAGS_transpose_4 := -DTRANSPOSE_VARIANT=4

TARGET_NAMES += transpose_5
TARGET_FLAGS_transpose_5 := -DTRANSPOSE_VARIANT=5

TARGET_NAMES += transpose_6
TARGET_FLAGS_transpose_6 := -DTRANSPOSE_VARIANT=6