KERNEL_NAME := gather_scatter
SRC := $(CURDIR)/src/gather_scatter.cu
CONFIG_DIR := $(CURDIR)/configs
TARGETS_FILE := $(CONFIG_DIR)/target_params.txt
PARAM_DEFINES := MY_BLOCKDIM
VERSION_DEFINE := GATHER_SCATTER_VARIANT
VERSIONS := 1

include ../../common/kernel.mk
