KERNEL_NAME := radix_sort
SRC := $(CURDIR)/src/radix_sort.cu
CONFIG_DIR := $(CURDIR)/configs
TARGETS_FILE := $(CONFIG_DIR)/target_params.txt
PARAM_DEFINES := MY_BLOCKDIM MY_BITS_PER_PASS
VERSION_DEFINE := RADIX_SORT_VARIANT
VERSIONS := 1

include ../../common/kernel.mk
